import me.modmuss50.mpp.ReleaseType

plugins {
	id "me.modmuss50.mod-publish-plugin" version "0.8.4"
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url "https://maven.terraformersmc.com/releases/" }
	maven { url "https://maven.isxander.dev/releases" }
	maven { url "https://api.modrinth.com/maven" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Mod Menu
	modApi "com.terraformersmc:modmenu:${project.mod_menu}"

	// YACL
	modImplementation "dev.isxander:yet-another-config-lib:${project.yacl}"

	// Fabrishot
	modCompileOnly "maven.modrinth:fabrishot:${project.fabrishot}"
}

processResources {
	def properties = [
			"version": project.version,
			"minecraft_min": minecraft_min,
			"fabric_version": fabric_version,
			"fabric_api_min": fabric_api_min
	]

	inputs.properties(properties)

	filesMatching("fabric.mod.json") {
		expand(properties)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishMods {
	file = remapJar.archiveFile
	changelog = rootProject.file("CHANGELOG.md").text
	type = ReleaseType.STABLE
	modLoaders.add("fabric")

	modrinth {
		projectId = "vevAjqG0"
		accessToken = providers.gradleProperty("modrinthToken")

		minecraftVersionRange {
			start = "1.21.5"
			end = "1.21.5"
		}

		requires("fabric-api", "yacl")
		optional("modmenu")
	}

	curseforge {
		projectId = "994872"
		projectSlug = "ijm-tweaks"
		accessToken = providers.gradleProperty("curseforgeToken")

		minecraftVersionRange {
			start = "1.21.5"
			end = "1.21.5"
		}

		javaVersions.add(JavaVersion.VERSION_21)

		clientRequired = true
		serverRequired = false

		requires("fabric-api", "yacl")
		optional("modmenu")
	}

	github {
		repository = "ItsJustMiaouss/ijm-tweaks"
		accessToken = providers.gradleProperty("githubToken")
		commitish = "1.21.5"
		tagName = "v${mod_version}"
	}
}
