import me.modmuss50.mpp.ReleaseType

plugins {
	id "me.modmuss50.mod-publish-plugin" version "1.1.0"
	id 'net.fabricmc.fabric-loom' version '1.14-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url = "https://maven.terraformersmc.com/releases/" }
	maven { url = "https://maven.isxander.dev/releases" }
	maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Mod Menu
	api "com.terraformersmc:modmenu:${project.mod_menu}"

	// YACL
	implementation "dev.isxander:yet-another-config-lib:${project.yacl}"

	// Fabrishot
	compileOnly "maven.modrinth:fabrishot:${project.fabrishot}"

	// Twelvemonkeys
	implementation("com.twelvemonkeys.imageio:imageio-core:3.12.0")
	implementation("com.twelvemonkeys.imageio:imageio-webp:3.12.0")

	include("com.twelvemonkeys.imageio:imageio-core:3.12.0")
	include("com.twelvemonkeys.imageio:imageio-webp:3.12.0")
}

processResources {
	def properties = [
			"version": project.version,
			"minecraft_min": minecraft_min,
			"fabric_version": fabric_version,
			"fabric_api_min": fabric_api_min
	]

	inputs.properties(properties)

	filesMatching("fabric.mod.json") {
		expand(properties)
	}
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release.set(25)
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishMods {
	file = tasks.named("jar").flatMap {it.archiveFile} as Provider<? extends RegularFile>
	changelog = rootProject.file("CHANGELOG.md").text
	type = ReleaseType.STABLE
	modLoaders.add("fabric")

	modrinth {
		projectId = "vevAjqG0"
		accessToken = providers.gradleProperty("modrinthToken")

		minecraftVersionRange {
			start = "26.1-snapshot-4"
			end = "26.1-snapshot-4"
		}

		requires("fabric-api", "yacl")
		optional("modmenu")
	}

	curseforge {
		projectId = "994872"
		projectSlug = "ijm-tweaks"
		accessToken = providers.gradleProperty("curseforgeToken")

		minecraftVersionRange {
			start = "26.1-snapshot-4"
			end = "26.1-snapshot-4"
		}
		javaVersions.add(JavaVersion.VERSION_25)
		clientRequired = true
		serverRequired = false

		requires("fabric-api", "yacl")
		optional("modmenu")
	}

	github {
		repository = "ItsJustMiaouss/ijm-tweaks"
		accessToken = providers.gradleProperty("githubToken")
		commitish = "26.1-snapshot-4"
		tagName = "v${mod_version}"
	}
}
