# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT
fabric_version=0.152.0+26.2

# Mod Properties
mod_version=1.8.0+26.2
maven_group=com.itsjustmiaouss
archives_base_name=ijm-tweaks

# Dependencies
minecraft_min=26.2
fabric_api_min=0.152.0+26.2

mod_menu=20.0.0-beta.2
yacl=3.9.4+26.2-fabric
fabrishot=1.17.0
sodium=0.9.0-beta.3+mc26.2r1