# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-snapshot-4
loader_version=0.18.4
fabric_version=0.142.1+26.1

# Mod Properties
mod_version=1.7.0+26.1
maven_group=com.itsjustmiaouss
archives_base_name=ijmtweaks

# Dependencies
minecraft_min=26.1-alpha.4
fabric_api_min=0.142.1+26.1

mod_menu=18.0.0-alpha.4
yacl=3.8.2+26.1.0-fabric
fabrishot=1.16.4