# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_version=0.161.0+26.3

# Mod Properties
mod_version=1.8.0+26.3
maven_group=com.itsjustmiaouss
archives_base_name=ijm-tweaks

# Dependencies
minecraft_min=26.3
fabric_api_min=0.161.0+26.3

mod_menu=21.0.0
yacl=3.9.7+26.3-fabric
fabrishot=1.17.0
sodium=0.9.2+mc26.3